import type { City, EventOpportunity, Place } from "./types";

export const months = ["May", "June", "July", "August", "September", "October"];

export const cities: City[] = [
  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    types: ["city", "sea", "culture", "food"],
    base_cost_per_person: 760,
    average_daily_cost: 55,
    social_density_score: 92,
    nightlife_score: 88,
    history_score: 86,
    food_culture_score: 84,
    mobility_score: 88,
    sea_access: true,
    crowd_pressure_by_month: { May: 54, June: 70, July: 88, August: 92, September: 72, October: 55 },
    seasonality_by_month: { May: 86, June: 89, July: 82, August: 78, September: 92, October: 88 },
    best_neighborhoods: ["Ruzafa", "El Carmen", "Cabanyal", "Malvarrosa"],
    risk_flags: ["Hot in August", "Central villas are rare"],
    nationality_mix_context: "Real city with local Spanish base, Erasmus, expats, and European beach tourism.",
    notes: "Best all-round city for social/culture/food/beach balance."
  },
  {
    id: "malta",
    name: "Malta / Sliema-St Julian's",
    country: "Malta",
    types: ["island", "sea", "nightlife", "history"],
    base_cost_per_person: 820,
    average_daily_cost: 60,
    social_density_score: 96,
    nightlife_score: 92,
    history_score: 90,
    food_culture_score: 78,
    mobility_score: 78,
    sea_access: true,
    crowd_pressure_by_month: { May: 70, June: 84, July: 95, August: 98, September: 82, October: 60 },
    seasonality_by_month: { May: 88, June: 92, July: 90, August: 86, September: 94, October: 84 },
    best_neighborhoods: ["Sliema", "Gzira", "St Julian's", "Valletta"],
    risk_flags: ["Paceville can be chaotic", "Summer price pressure"],
    nationality_mix_context: "English-speaking, tourist-heavy, language students, remote workers, UK/Italy/EU mix.",
    notes: "Highest probability of casual international social interaction."
  },
  {
    id: "malaga",
    name: "Malaga",
    country: "Spain",
    types: ["city", "sea", "food", "nightlife"],
    base_cost_per_person: 790,
    average_daily_cost: 58,
    social_density_score: 88,
    nightlife_score: 87,
    history_score: 88,
    food_culture_score: 86,
    mobility_score: 86,
    sea_access: true,
    crowd_pressure_by_month: { May: 56, June: 74, July: 90, August: 94, September: 78, October: 58 },
    seasonality_by_month: { May: 88, June: 88, July: 82, August: 80, September: 90, October: 88 },
    best_neighborhoods: ["Centro Historico", "Soho", "La Malagueta", "Pedregalejo"],
    risk_flags: ["Center can be crowded", "August heat"],
    nationality_mix_context: "Spanish local base with UK, Dutch, German, French, Italian, US tourist flows.",
    notes: "Compact beach/history/nightlife package."
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    types: ["city", "nightlife", "culture", "remote-work"],
    base_cost_per_person: 850,
    average_daily_cost: 62,
    social_density_score: 94,
    nightlife_score: 91,
    history_score: 92,
    food_culture_score: 82,
    mobility_score: 80,
    sea_access: false,
    crowd_pressure_by_month: { May: 64, June: 78, July: 86, August: 88, September: 74, October: 60 },
    seasonality_by_month: { May: 90, June: 88, July: 84, August: 82, September: 92, October: 90 },
    best_neighborhoods: ["Bairro Alto", "Cais do Sodre", "Alfama", "Principe Real"],
    risk_flags: ["Not directly beach-first", "Hills and transfer friction"],
    nationality_mix_context: "Very international, digital nomads, students, tourists, Portuguese local base.",
    notes: "World-class social/culture city but not a simple beach-villa trip."
  },
  {
    id: "split",
    name: "Split",
    country: "Croatia",
    types: ["historic-sea", "island", "summer"],
    base_cost_per_person: 790,
    average_daily_cost: 52,
    social_density_score: 83,
    nightlife_score: 80,
    history_score: 94,
    food_culture_score: 78,
    mobility_score: 72,
    sea_access: true,
    crowd_pressure_by_month: { May: 42, June: 74, July: 96, August: 98, September: 70, October: 35 },
    seasonality_by_month: { May: 78, June: 88, July: 92, August: 90, September: 88, October: 70 },
    best_neighborhoods: ["Old Town", "Bacvice", "Znjan"],
    risk_flags: ["Highly seasonal", "Old town crowding"],
    nationality_mix_context: "Adriatic summer traveler mix with German, Austrian, Slovenian, Polish, UK, Dutch tourists.",
    notes: "Best cinematic historic-sea summer option."
  }
];

export const places: Place[] = [
  {
    id: "cabanal-seafood-terrace",
    name: "Cabanal Seafood Terrace",
    type: "seafood restaurant",
    city_id: "valencia",
    neighborhood: "Cabanyal",
    ambience_tags: ["coastal", "social", "group-friendly"],
    feature_tags: ["sea", "seafood", "local_food", "terrace", "young_adults", "international_crowd"],
    price_level: 3,
    social_ambience_score: 78,
    evidence_confidence_score: 82,
    business_confirmed: true,
    good_for: ["groups", "dates", "recovery day"],
    notes: "Coastal seafood, terrace, group-friendly social dinner."
  },
  {
    id: "ruzafa-matcha-bakes",
    name: "Ruzafa Matcha & Bakes",
    type: "cafe",
    city_id: "valencia",
    neighborhood: "Ruzafa",
    ambience_tags: ["warm", "creative", "daytime social"],
    feature_tags: ["matcha", "baked_goods", "young_adults", "international_crowd", "laptop_friendly", "coworking"],
    price_level: 2,
    social_ambience_score: 88,
    evidence_confidence_score: 76,
    business_confirmed: true,
    good_for: ["remote work", "meeting people", "solo travelers"],
    notes: "Specialty drinks, baked goods, international cafe culture."
  },
  {
    id: "old-town-sports-social",
    name: "Old Town Sports Social",
    type: "sports bar",
    city_id: "malaga",
    neighborhood: "Centro",
    ambience_tags: ["high-energy", "casual", "pre-drinks"],
    feature_tags: ["sports_tv", "bars", "young_adults", "international_crowd", "live_music"],
    price_level: 2,
    social_ambience_score: 84,
    evidence_confidence_score: 70,
    business_confirmed: false,
    good_for: ["watching sports", "groups", "pre-drinks"],
    notes: "Sports TV and international social bar energy."
  },
  {
    id: "harbour-cowork-terrace",
    name: "Harbour Cowork Terrace",
    type: "coworking",
    city_id: "malta",
    neighborhood: "Sliema",
    ambience_tags: ["productive", "networking", "sea-view"],
    feature_tags: ["coworking", "laptop_friendly", "terrace", "startup_events", "international_crowd"],
    price_level: 3,
    social_ambience_score: 80,
    evidence_confidence_score: 78,
    business_confirmed: true,
    good_for: ["remote work", "meeting people", "solo travelers"],
    notes: "Coworking plus terrace and opt-in networking."
  }
];

export const events: EventOpportunity[] = [
  { id: "language-exchange", name: "Language exchange night", category: "language exchange", city_id: "valencia", tags: ["language_exchange", "international_crowd", "young_adults"], notes: "Opt-in social environment." },
  { id: "beach-volleyball", name: "Beach volleyball open game", category: "sport", city_id: "malaga", tags: ["beach_sports", "sea", "young_adults"], notes: "Daytime social sport context." },
  { id: "startup-meetup", name: "Startup / digital nomad meetup", category: "networking", city_id: "lisbon", tags: ["startup_events", "coworking", "international_crowd"], notes: "Opt-in professional/social context." },
  { id: "football-viewing", name: "Football viewing night", category: "sports bar", city_id: "malaga", tags: ["sports_tv", "bars", "young_adults"], notes: "Good for groups and casual conversation." }
];
